export const WAIT_AND_PLAY_ANIMATION = 'WAIT_AND_PLAY_ANIMATION';
export const CHANGE_SECTION = 'CHANGE_SECTION';
export const CHANGE_THEME = 'CHANGE_THEME';
export const STACK_CHANGED = 'STACK_CHANGED';